### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by drzax** [abcnews/odyssey-audio-visual-plugin#1]
Hey @phocks — could you please add a little more documentation to the readme so it's more clear what this is for and how to use it?

**Comment by phocks** [comment]
Yes indeed. Good thinking!

**Comment by phocks** [comment]
@drzax could you please add me as admin on this so I can change the description and throw in a URL (why is this an admin only thing??)

**Comment by drzax** [comment]
@phocks Done

**Comment by phocks** [comment]
@drzax whoops I totally forgot that I was going to brush up the docs on this. I've just converted it to TypeScript and PL compatible. So will do the documentation too.

**Comment by phocks** [comment]
#11 added basic instructions. May expand later if we start using this more.
